### ISSUE TITLE
NullpointerException while using code with Neural Network Model 

### ISSUE THREAD

**Issue by RamakrishnaAddanki** [jpmml/jpmml-pig#1]
Hi

I am testing the libraries with Neural Network Model and i am getting NullPointerException as i got the same while testing with Hive and PostgreSQL. can u please help me out.

Pig Stack Trace
---------------
ERROR 1066: Unable to open iterator for alias B. Backend error : org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing [POUserFunc (Name: POUserFunc(org.jpmml.pig.DecisionTreeIris)[tuple] - scope-219 Operator Key: scope-219) children: null at []]: java.lang.NullPointerException

org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1066: Unable to open iterator for alias B. Backend error : org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing [POUserFunc (Name: POUserFunc(org.jpmml.pig.DecisionTreeIris)[tuple] - scope-219 Operator Key: scope-219) children: null at []]: java.lang.NullPointerException
   at org.apache.pig.PigServer.openIterator(PigServer.java:966)
   at org.apache.pig.tools.grunt.GruntParser.processDump(GruntParser.java:754)
   at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:376)
   at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:230)
   at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:205)
   at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:66)
   at org.apache.pig.Main.run(Main.java:565)
   at org.apache.pig.Main.main(Main.java:177)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:606)
   at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
   at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing [POUserFunc (Name: POUserFunc(org.jpmml.pig.DecisionTreeIris)[tuple] - scope-219 Operator Key: scope-219) children: null at []]: java.lang.NullPointerException
   at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher.getStats(MapReduceLauncher.java:819)
   at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher.launchPig(MapReduceLauncher.java:452)
   at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.launchPig(HExecutionEngine.java:304)
   at org.apache.pig.PigServer.launchPlan(PigServer.java:1431)
   at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1416)
   at org.apache.pig.PigServer.storeEx(PigServer.java:1075)
   at org.apache.pig.PigServer.store(PigServer.java:1038)
   at org.apache.pig.PigServer.openIterator(PigServer.java:951)
   ... 13 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing [POUserFunc (Name: POUserFunc(org.jpmml.pig.DecisionTreeIris)[tuple] - scope-219 Operator Key: scope-219) children: null at []]: java.lang.NullPointerException
   at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:366)
   at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:400)
   at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:317)
   at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapBase.runPipeline(PigGenericMapBase.java:279)
   at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapBase.map(PigGenericMapBase.java:274)
   at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapBase.map(PigGenericMapBase.java:64)
   at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
   at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
   at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
   at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
   at java.security.AccessController.doPrivileged(Native Method)
   at javax.security.auth.Subject.doAs(Subject.java:415)
   at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
   at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)
Caused by: java.lang.NullPointerException
   at org.jpmml.evaluator.NeuralNetworkEvaluator.evaluateRaw(NeuralNetworkEvaluator.java:253)
   at org.jpmml.evaluator.NeuralNetworkEvaluator.evaluateClassification(NeuralNetworkEvaluator.java:158)
   at org.jpmml.evaluator.NeuralNetworkEvaluator.evaluate(NeuralNetworkEvaluator.java:97)
   at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:230)
   at org.jpmml.pig.PMMLUtil.evaluateComplex(PMMLUtil.java:78)
   at org.jpmml.pig.DecisionTreeIris.exec(DecisionTreeIris.java:31)
   at org.jpmml.pig.DecisionTreeIris.exec(DecisionTreeIris.java:27)
   at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:326)
   at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNextTuple(POUserFunc.java:365)
   at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:361)

**Comment by vruusmann** [comment]
The relevant part of your exception stack trace is the following:
```
Caused by: java.lang.NullPointerException
at org.jpmml.evaluator.NeuralNetworkEvaluator.evaluateRaw(NeuralNetworkEvaluator.java:253)
at org.jpmml.evaluator.NeuralNetworkEvaluator.evaluateClassification(NeuralNetworkEvaluator.java:158)
at org.jpmml.evaluator.NeuralNetworkEvaluator.evaluate(NeuralNetworkEvaluator.java:97)
```

This exception occurs, because there is a `Neuron` element, which doesn't specify a non-null value for the `bias` attribute. This is a perfectly legal thing to do, because the `Neuron@bias` attribute is optional according to the PMML specification.

JPMML-Pig depends on JPMML-Evaluator library version 1.1.13, which is awfully outdated. [The handling of the `Node@bias` attribute has been fixed](https://github.com/jpmml/jpmml-evaluator/commit/0ab5e9915c391a741fb8f9740b93f70528f3321d) in JPMML-Evaluator library version 1.2.13 and newer.

So, if you want to solve this NPE, you need to update the JPMML-Evaluator dependency to the latest stable version.

**Comment by RamakrishnaAddanki** [comment]
Thank you very much for your reply 

actually i just installed these JPMML-Evaluator libraries into my repo and in the above jpmml-pig code where do i need to change this JPMML-Evaluator dependency whether it is in pmml-pig pom.xml or jpmml-pig pom.xml or pmml-pig-example pom.xml i was confused and there is no dependency like this in any of those pom   

<dependency>
    <groupId>org.jpmml</groupId>
    <artifactId>pmml-evaluator</artifactId>
    <version>1.2.15</version>
</dependency>

**Comment by RamakrishnaAddanki** [comment]
Hi 
When am i adding the latest JPMML-Evaluator dependency the build is failing and error is 

 --- maven-clean-plugin:2.5:clean (default-clean) @ pmml-pig ---
[INFO] Deleting /opt/jpmml-pig/pmml-pig/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ pmml-pig ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /opt/jpmml-pig/pmml-pig/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ pmml-pig ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /opt/jpmml-pig/pmml-pig/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /opt/jpmml-pig/pmml-pig/src/main/java/org/jpmml/pig/PMMLUtil.java:[202,55] cannot access org.jpmml.manager.ModelManager
  class file for org.jpmml.manager.ModelManager not found
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] JPMML-Pig .......................................... SUCCESS [  0.920 s]
[INFO] JPMML Pig .......................................... FAILURE [  2.830 s]
[INFO] JPMML Pig example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.922 s
[INFO] Finished at: 2016-08-25T07:08:19+00:00
[INFO] Final Memory: 19M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project pmml-pig: Compilation failure
[ERROR] /opt/jpmml-pig/pmml-pig/src/main/java/org/jpmml/pig/PMMLUtil.java:[202,55] cannot access org.jpmml.manager.ModelManager
[ERROR] class file for org.jpmml.manager.ModelManager not found
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pmml-pig
